/* Materialize */

import './js/cash'
import './js/component'
import './js/global'
import './js/anime.min'

import './js/collapsible'
import './js/dropdown'
import './js/modal'
import './js/materialbox'
import './js/parallax'
import './js/tabs'
import './js/tooltip'
import './js/waves'
import './js/toasts'
import './js/sidenav'
import './js/scrollspy'
import './js/autocomplete'
import './js/forms'
import './js/slider'
import './js/cards'
import './js/chips'
import './js/pushpin'
import './js/buttons'
import './js/datepicker'
import './js/timepicker'
import './js/characterCounter'
import './js/carousel'
import './js/tapTarget'
import './js/select'
import './js/range'